### ISSUE TITLE
Experience report: DICOM->GLM Stats

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-hirni#120]
**Target:** Do a full GLM analysis with all the great machinery in the cmdline. Preferably without intermediate scriting.

**Bottom line:** All actually tricky parts of the workflow work well, but quite a few minor issue make it needlessly hard to succeed within a reasonable time frame. Here is the protocol with comment and links to issues:

### study raw data

Fresh dataset
```sh
datalad create -c hirni raw
```
  - [ ] overcomplicated due to https://github.com/psychoinformatics-de/datalad-hirni/issues/116

Import DICOM (will create subdatasets inside)
```sh
datalad hirni-import-dcm -d raw \
   --anon-subject 001 \
  https://github.com/datalad/example-dicom-structural/archive/master.tar.gz \
  acq1
```
```sh
datalad hirni-import-dcm -d raw \
   --anon-subject 001 \
  https://github.com/datalad/example-dicom-functional/archive/master.tar.gz \
  acq2
```
- [ ] slow due to https://github.com/psychoinformatics-de/datalad-hirni/issues/117

Add non-DICOM study data
```sh
#datalad download-url -d raw -O raw/acq2/events.tsv https://github.com/datalad/example-dicom-functional/raw/master/events.tsv
git -C raw/acq2 \
  annex \
  addurl https://github.com/datalad/example-dicom-functional/raw/master/events.tsv \
  --file events.tsv
datalad save -d raw -m "Added stimulation protocol for acquisition 2"
```
- [ ] needs above workaround: https://github.com/datalad/datalad/issues/3468

Configure a "converter" for the stimulation protocol, to be used for BIDSification
```sh
datalad hirni-spec4anything -d raw \
  acq2/events.tsv \
  --properties '{"procedures": {"procedure-name": "copy-converter", "procedure-call": "bash {script} {{location}} {ds}/sub-{{bids-subject}}/func/sub-{{bids-subject}}_task-{{bids-task}}_run-{{bids-run}}_events.tsv"}, "type": "events_file"}'
```
- [ ] working in this form, but actually wrong: https://github.com/psychoinformatics-de/datalad-hirni/issues/118

### BIDSification

BIDS-compliant dataset is a fresh dataset
```sh
datalad create -c bids bids
```

that has the study raw dataset linked
```sh
datalad -C bids install -d . -r -s ../raw sourcedata
```
- [ ] overcomplicated due to https://github.com/datalad/datalad/issues/3469

Convert everything to BIDS by selection all desired studyspecs.
```sh
cd bids
datalad hirni-spec2bids -d . --anonymize $(find . -name studyspec.json)
cd ..
```
- [ ] overcomplicated due to https://github.com/psychoinformatics-de/datalad-hirni/issues/119

### analysis

Any analysis is also a fresh dataset
```sh
datalad create -c yoda analysis
cd analysis
```

that has the BIDSified data linked as input
```sh
datalad install -d . -s ../bids inputs/rawdata
```

Build an FSL analysis container based on a recipe (note: takes a fraction of the download time from singularity hub). Analysis in a container == better chances to reproduce.

Get the container build specifications.
```sh
datalad download-url \
  -m 'FSL container spec' \
  -O code/singularity.fsl \
  https://github.com/psychoinformatics-de/datalad-hirni/raw/master/datalad_hirni/tests/resources/fsl-simg-spec
```

Build the actual container (include a permission fix to be able to get the image file tracked in the dataset).
```sh
# singularity doesn't create the target dir
mkdir -p .datalad/environments
# build container image
datalad run \
  -i code/singularity.fsl \
  -o .datalad/environments/fsl.simg \
  "sudo bash -x -c 'singularity build {outputs} {inputs} && sudo chown --reference .datalad {outputs}'"
# register container for datalad
datalad containers-add -d . \
  -i .datalad/environments/fsl.simg \
  --call-fmt 'singularity exec {img} {cmd}' \
  fsl
```

Add the remaining pieces to be able to compute a GLM analysis (a script to convert the stimulation log into FSL EV3 files, and a template analysis configuration).
```sh
datalad download-url -m 'Analysis template+code' \
  -O code/ \
  https://github.com/psychoinformatics-de/datalad-hirni/raw/master/datalad_hirni/tests/resources/events2ev3.sh \
  https://github.com/psychoinformatics-de/datalad-hirni/raw/master/datalad_hirni/tests/resources/ffa_design.fsf
```

Convert the stimulus log into EV3 files and build an actual analysis configuration for `sub-001` from the template.
```sh
# build onset files for FSL
datalad run -m "Build FSL EV3 design files" \
  -i inputs/rawdata/sub-001/func/sub-001_task-oneback_run-01_events.tsv \
  -o sub-001/onsets \
  'bash code/events2ev3.sh sub-001 {inputs}'

# build analysis config for FSL
datalad run -m "FSL FEAT analysis config script" \
  -i code/ffa_design.fsf \
  -o sub-001/1stlvl_design.fsf \
  "bash -c 'sed -e \"s,##BASEPATH##,{pwd},g\" -e \"s,##SUB##,sub-001,g\" {inputs} > {outputs}'"
```

Compute the GLM analysis
```sh
datalad containers-run -n fsl -m 'sub-001 1st-level GLM' \
  -i sub-001/1stlvl_design.fsf \
  -i sub-001/onsets -i inputs/rawdata/sub-001/func/sub-001_task-oneback_run-01_bold.nii.gz \
  -o sub-001/1stlvl_glm.feat \
  'feat {inputs[0]}'
```

Inform the dataset that it carries FSL FEAT, and `run` provenance metadata. And pull it out.
```sh
git config --file .datalad/config --add datalad.metadata.nativetype metalad_fslfeat
git config --file .datalad/config --add datalad.metadata.nativetype metalad_runprov
datalad save

datalad meta-aggregate -r
```

**Comment by mih** [comment]
@cmaumet @jbpoline which of the metadata-related bits (last section) should appear on the poster, or rather, how to tweak them to become relevant?

@dkeator NIDM-E would be next on my TODO list, in order to bring proper metadata on the analysis inputs into the picture ... likely post-OHBM
